version: '3'

services:

  omero-db:
    image: postgres:10-alpine
    networks:
      ome_seadragon_env:
        aliases:
          - ome-pg-server
    environment:
      - POSTGRES_DB=omero
      - POSTGRES_USER=omero
      - POSTGRES_PASSWORD=omero
    volumes:
      - ome-pg-data:/var/lib/postgresql/data

  redis-server:
    image: redis:5.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      ome_seadragon_env:
        aliases:
          - redis-server
    volumes:
      - redis-data:/data

  omero-server:
    image: openmicroscopy/omero-server:5.5.1-1
    depends_on:
      - omero-db
    networks:
      ome_seadragon_env:
        aliases:
          - omero-server
    ports:
      - "4063:4063"
      - "4064:4064"
    environment:
      - ROOTPASS=omero
      - CONFIG_omero_db_host=ome-pg-server
      - CONFIG_omero_db_user=omero
      - CONFIG_omero_db_pass=omero
      - CONFIG_omero_db_name=omero
    volumes:
      - ome-data-dir:/OMERO
      - ome-server-var:/opt/omero/server/OMERO.server/var

  ome_seadragon-web:
    image: crs4/ome_seadragon-web:0.6.15-ome5.5.1
    depends_on:
      - omero-server
      - redis-server
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'redis-server:6379', '--',
                 '/usr/local/bin/wait-for-it.sh', 'omero-server:4063', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/wait-for-it.sh', 'omero-server:4064', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/entrypoint.sh']
    networks:
      ome_seadragon_env:
        aliases:
          - ome_seadragon-web
    environment:
      - ROOTPASS=omero
      - OMEROHOST=omero-server
      - REDISHOST=redis-server
      - IMAGES_REPOSITORY=/OMERO/
      - GW_USER_NAME=ome_gw
      - GW_USER_PASS=omero
    volumes:
      - ome-data-dir:/OMERO

  ome_seadragon-nginx:
    image: crs4/ome_seadragon-nginx:0.6.15-ome5.5.1
    depends_on:
      - ome_seadragon-web
      # - nginx-proxy
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'ome_seadragon-web:4080', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/entrypoint.sh']
    networks:
      ome_seadragon_env:
        aliases:
          - ome_seadragon-nginx
          - ome-seadragon.local
    ports:
      - "80:80"
    environment:
      - OMEROWEBHOST=ome_seadragon-web

volumes:
  ome-pg-data:
  ome-server-var:
  ome-data-dir:
  redis-data:

networks:
  ome_seadragon_env:
